### ISSUE TITLE
How to change the keyboard layout?

### ISSUE THREAD

**Issue by m-asyua** [humphd/browser-vm#11]
Is there a way to change my keyboard layout? (menuconfig or inittab? I can customize image by menuconfig and build the kernel in Docker,  it works well.)

**Comment by humphd** [comment]
I'm honestly not sure.  Whatever you can do via menuconfig will work, so I'd research in that direction.

**Comment by m-asyua** [comment]
Thank you for your reply.
I found the option in menuconfig:
->Target packages
->Hardware handling
[ ]kbd

I can use 'loadkeys' command, I made a script under /etc/init.d/ for loadkeys (e.g., loadkeys test.map), and it works!


<img width="324" alt="key1" src="https://user-images.githubusercontent.com/83494645/152665254-eec678a1-9ca5-44ed-b3aa-00eff73b3919.png">

**Comment by humphd** [comment]
Awesome!
